### ISSUE TITLE
[BUG] Error when reloading script with brig command

### ISSUE THREAD

**Issue by envizar** [ShaneBeee/SkBriggy#1]
### What happened?

```
[14:14:14 ERROR]: Caught previously unhandled exception :
[14:14:14 ERROR]: Paper Async Command Builder Thread Pool - 24
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:487) ~[?:?]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:451) ~[?:?]
        at net.minecraft.commands.Commands.lambda$sendCommands$4(Commands.java:424) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

Try to reload script with brig command

### Expected behavior

Not throw error

### SkBriggy Version

1.0.0-beta2

### Server Version

Purpur 1.20.1

### Skript Info

```
[14:17:28 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:17:28 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:17:28 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:17:28 INFO]: [Skript] Server Version: git-Purpur-2025 (MC: 1.20.1)
[14:17:28 INFO]: [Skript] Skript Version: 2.7.0-beta3 (selfbuilt-unknown)
[14:17:28 INFO]: [Skript] Installed Skript Addons: 
[14:17:28 INFO]: [Skript]  - PoaSK v2.5
[14:17:28 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[14:17:28 INFO]: [Skript]  - skript-particle v1.0.2-beta (https://github.com/sovdeeth/skript-particle)
[14:17:28 INFO]: [Skript]  - skript-reflect v2.3.1-for-skript-beta (https://github.com/TPGamesNL/skript-reflect)
[14:17:28 INFO]: [Skript]  - Lusk v1.0.4-beta2
[14:17:28 INFO]: [Skript]  - Bitshift v1.0
[14:17:28 INFO]: [Skript]  - SkQuery v4.1.10
[14:17:28 INFO]: [Skript]  - SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
[14:17:28 INFO]: [Skript]  - SkJson v2.9 (https://github.com/SkJsonTeam/SkJson)
[14:17:28 INFO]: [Skript]  - SkBriggy v1.0.0-beta2
[14:17:28 INFO]: [Skript]  - Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
[14:17:28 INFO]: [Skript]  - ItemsAdder v3.5.0c-r3 (devs.beer)
[14:17:28 INFO]: [Skript] Installed dependencies: 
[14:17:28 INFO]: [Skript]  - Vault v1.7.3-b131
[14:17:28 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

**Comment by ShaneBeee** [comment]
does anybody out there read change logs?

<img width="1455" alt="Screenshot 2023-08-12 at 8 06 31 AM" src="https://github.com/ShaneBeee/SkBriggy/assets/20008482/fc52b775-86c4-4fff-b988-d200f0ce1ec7">
